spring:
  datasource:
    url: jdbc:mysql://localhost:3306/no_ingredient_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: "[HathCock]8120!"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # \uD14C\uC774\uBE14 \uAD6C\uC870\uB97C \uC720\uC9C0\uD558\uBA70 \uBCC0\uACBD\uC0AC\uD56D\uB9CC \uBC18\uC601
    show-sql: true     # \uC2E4\uD589\uB418\uB294 SQL\uC744 \uCF58\uC194\uC5D0 \uCD9C\uB825
    properties:
      hibernate:
        format_sql: true                  # SQL\uC744 \uC815\uB82C\uD574\uC11C \uCD9C\uB825
    defer-datasource-initialization: true # data.sql\uC774 \uD14C\uC774\uBE14 \uC0DD\uC131 \uD6C4 \uC2E4\uD589\uB418\uB3C4\uB85D \uC124\uC815